version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: CharityShop/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db; Port=5432; Database=CharityShopDb; Uid=postgres; Pwd=mysecretpassword; Pooling=true"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure

  db:
    image: "postgres:alpine"
    environment:
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=CharityShopDb"
    ports:
      - "5432:5432"